import type { App, Component } from 'vue'
import {
  ElAlert,
  ElAvatar,
  ElBadge,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElButton,
  ElDatePicker,
  ElDescriptions,
  ElDescriptionsItem,
  ElDialog,
  ElDrawer,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElEmpty,
  ElForm,
  ElFormItem,
  ElIcon,
  ElInput,
  ElInputNumber,
  ElLoadingDirective,
  ElMenu,
  ElMenuItem,
  ElOption,
  ElPagination,
  ElRadio,
  ElRadioGroup,
  ElScrollbar,
  ElSelect,
  ElSpace,
  ElSubMenu,
  ElSwitch,
  ElTable,
  ElTableColumn,
  ElTabPane,
  ElTabs,
  ElTag,
  ElTooltip,
  ElTransfer,
  ElTree,
  ElTreeSelect,
} from 'element-plus'

const elementComponents: Component[] = [
  ElAlert,
  ElAvatar,
  ElBadge,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElButton,
  ElDatePicker,
  ElDescriptions,
  ElDescriptionsItem,
  ElDialog,
  ElDrawer,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElEmpty,
  ElForm,
  ElFormItem,
  ElIcon,
  ElInput,
  ElInputNumber,
  ElMenu,
  ElMenuItem,
  ElOption,
  ElPagination,
  ElRadio,
  ElRadioGroup,
  ElScrollbar,
  ElSelect,
  ElSpace,
  ElSubMenu,
  ElSwitch,
  ElTable,
  ElTableColumn,
  ElTabPane,
  ElTabs,
  ElTag,
  ElTooltip,
  ElTransfer,
  ElTree,
  ElTreeSelect,
]

export const setupElementPlus = (app: App) => {
  // 统一在这里注册当前项目实际用到的组件，避免整库注入把公共包越滚越大。
  elementComponents.forEach((component) => {
    if (component.name) {
      app.component(component.name, component)
    }
  })

  // 全局注册 loading 指令，兼容页面里的 v-loading 用法。
  app.directive('loading', ElLoadingDirective)
}
